const fs = require('fs');
const path = './data/planosPE.ts';
let content = fs.readFileSync(path, 'utf8');

const newIlgch = `    'ilgch': [
        { data: '28/08', tri: '2º Tri', modulo: 'Introdução', titulo: 'Aulas Suspensas', desc: 'Aulas suspensas por motivos de força maior.', status: 'concluido', resumo: \`🎯 **Objetivo da Aula:** Sem aula por motivo de força maior.\` },
        { data: '04/09', tri: '2º Tri', modulo: 'Introdução', titulo: 'O que é ILGCH / IFFC / IFLA?', desc: 'Apresentação das matérias eletivas exigidas pela SEEDUC RJ.', status: 'concluido', resumo: \`🎯 **Objetivo da Aula:** Apresentar a disciplina e seus eixos formativos.\\n\\n🗣️ **Dinâmica:**\\n• O que significa Itinerário Formativo?\\n• Ciências Humanas e Sociais Aplicadas.\\n\\n📜 **Reflexão:** Qual a importância das disciplinas eletivas na formação do aluno?\` },
        { data: '11/09', tri: '3º Tri', modulo: 'Identidade', titulo: 'Identidade e Sociedade', desc: 'Debate sobre Frantz Fanon e Cida Bento.', resumo: \`🎯 **Objetivo da Aula:** Debater construções identitárias.\\n\\n🗣️ **Dinâmica:**\\n• Leitura sobre Fanon.\\n• Conceito de branquitude por Cida Bento.\\n\\n📜 **Reflexão:** A identidade é algo dado ou construído?\` },
        { data: '18/09', tri: '3º Tri', modulo: 'Racismo', titulo: 'Racismo Estrutural e Recreativo', desc: 'Debate sobre o racismo invisível e estrutural, exemplos na segregação, África do Sul, Brasil, Jim Crow e Blackface.', resumo: \`🎯 **Objetivo da Aula:** Compreender as nuances do racismo invisível e estrutural.\\n\\n🗣️ **Dinâmica:**\\n• Apresentação de slides com casos reais: Segregação, África do Sul, Jim Crow e Blackface no Brasil e no mundo.\\n\\n📜 **Reflexão:** Como o humor recreativo mascara preconceitos estruturais?\` },
        { data: '25/09', tri: '3º Tri', modulo: 'Identidade', titulo: 'Negro vs Preto e o Pardismo no Brasil', desc: 'Autodeclaração, pardismo e Fanon. Passar trabalho sobre os povos originários.', trabalho: 'passar', resumo: \`🎯 **Objetivo da Aula:** Diferenciar negro e preto politicamente e estatisticamente.\\n\\n🗣️ **Dinâmica:**\\n• O mito da democracia racial e o "pardismo" influenciado pelas reflexões de Fanon.\\n• Divisão dos grupos para o trabalho trimestral.\\n\\n⚠️ **TRABALHO DE PESQUISA (Apresentação e Escrito):**\\n\\n📋 **O QUE FAZER:** Trabalho em grupo sobre os Povos Originários das 5 regiões do Brasil antes da grande invasão (1500) e o cenário atual.\\n\\n📑 **ESTRUTURA OBRIGATÓRIA DO TRABALHO ESCRITO:**\\n1. **Capa:** Nome do CIEP, Disciplina (ILGCH), Nome do Professor, Nomes e números de todos os componentes do grupo, Turma e Ano.\\n2. **Introdução:** Apresentação geral do tema e da região do Brasil escolhida pelo grupo.\\n3. **Desenvolvimento (Tópicos obrigatórios):**\\n   - Apresentar no mínimo **3 povos originários** da região escolhida.\\n   - Como era a estrutura social, cultura e economia desses povos **antes de 1500**?\\n   - Qual o **cenário atual** desses povos? (Lutas por demarcação, preservação cultural, ameaças contemporâneas).\\n4. **Conclusão:** Reflexão do grupo sobre a importância da preservação das culturas originárias.\\n5. **Referências:** Citar os livros, sites ou documentários pesquisados.\\n\\n🎤 **SOBRE A APRESENTAÇÃO:**\\n• Todos do grupo devem falar.\\n• Podem utilizar cartazes, slides ou outros recursos visuais.\\n• Data das apresentações: 23/10.\` },
        { data: '02/10', tri: '3º Tri', modulo: 'Povos Originários', titulo: 'Ailton Krenak', desc: 'A representatividade de Ailton Krenak e suas "ideias para adiar o fim do mundo".', resumo: \`🎯 **Objetivo da Aula:** Conhecer o pensamento do líder indígena Ailton Krenak.\\n\\n🗣️ **Dinâmica:**\\n• A importância da obra de Krenak.\\n• Sua entrada na Academia Brasileira de Letras.\\n\\n📜 **Reflexão:** O que significa "adiar o fim do mundo"?\` },
        { data: '09/10', tri: '3º Tri', modulo: 'Povos Originários', titulo: 'Formação das Sociedades Globais', desc: 'A contribuição dos povos originários em cada continente.', resumo: \`🎯 **Objetivo da Aula:** Analisar a fundação das sociedades sob a ótica dos povos nativos.\\n\\n🗣️ **Dinâmica:**\\n• O apagamento dos nativos.\\n• Estruturas sociais, econômicas e culturais antes de 1500.\\n\\n📜 **Reflexão:** O que a nossa sociedade atual deve às engenharias dos povos nativos?\` },
        { data: '16/10', tri: '3º Tri', modulo: 'Recesso', titulo: 'Semana do Saco Cheio / Prof', desc: 'Recesso do Dia do Professor.', resumo: \`🎯 **Objetivo da Aula:** Recesso - Sem aula.\` },
        { data: '23/10', tri: '3º Tri', modulo: 'Seminários', titulo: 'Apresentações: Povos Originários', destaque: true, desc: 'Apresentação de todos os grupos sobre povos das 5 regiões do Brasil.', resumo: \`🎯 **Objetivo da Aula:** Socializar conhecimento sobre a cultura e concluir as apresentações avaliativas.\\n\\n🗣️ **Dinâmica:**\\n• Apresentação de todos os grupos.\\n• Fechamento e análise comparada das etnias pesquisadas.\` },
        { data: '30/10', tri: '3º Tri', modulo: 'Políticas Públicas', titulo: 'A Guerra pela sua Mente: Algoritmos e Saúde Mental', desc: 'Análise de redes sociais, dopamina, tempo de tela e reterritorialização do próprio corpo.', resumo: \`🎯 **Objetivo da Aula:** Compreender o impacto neuroquímico e corporal do uso de redes sociais, aprendendo estratégias práticas de decolonização do tempo e do espaço físico.\\n\\n🗣️ **ROTEIRO DE FALA DO PROFESSOR (PASSO A PASSO):**\\n\\n📢 **1. INTRODUÇÃO (Acolhimento - 5 min):**\\n"Bom dia, pessoal! Hoje nós vamos falar sobre uma guerra invisível que está acontecendo agora mesmo, neste exato segundo, dentro do seu bolso. Quem aqui olhou o celular nos últimos 15 minutos? E por quê? Não é bronca! Quero que vocês pensem: vocês escolheram abri-lo ou sentiram uma 'coceira' física na mão? Hoje vamos entender a química do nosso cérebro, como as gigantes da tecnologia vendem nosso tempo e como podemos recuperar o comando."\\n\\n🧠 **2. A ARMADILHA DA DOPAMINA (10 min):**\\n"A dopamina não é o hormônio do prazer, mas do DESEJO e da expectativa! No feed infinito (TikTok/Reels), o algoritmo funciona como uma máquina caça-níqueis. Ele intercala posts sem graça com posts sensacionais. Esse padrão incerto vicia seu cérebro e cansa sua mente. Após 20 minutos disso, sua capacidade de focar despenca. Vamos abrir agora o celular em 'Tempo de Tela' nas configurações e ver quem tem a coragem de falar o seu tempo real de uso de ontem?"\\n\\n🧘‍♂️ **3. CORPO IMÓVEL x CÉREBRO ACELERADO (10 min):**\\n"Enquanto o cérebro voa a mil por hora, o corpo está curvado e estático. A cabeça inclinada joga um peso de até 27kg na coluna cervical (Tech Neck)! Além disso, usar o celular antes de dormir bloqueia a melatonina, gerando um cansaço crônico. A boa notícia é que esportes liberam endorfina e serotonina reais, limpando a mente. Vamos todos ficar de pé por 10 segundos, alinhar a postura, respirar fundo e sentir o alívio imediato na coluna. Sinta seu corpo de verdade!"\\n\\n🌐 **4. QUEM COMANDA SUA IDENTIDADE? (10 min):**\\n"Se você não paga pelo produto, o produto é você: eles vendem seu tempo de vida para anunciantes. Decolonizar o feed significa retomar suas escolhas reais e o comando de sua rotina. Como hack de atenção: desativem notificações inúteis, deixem o celular longe do quarto ao dormir e pratiquem atividades físicas."\\n\\n🔥 **5. DEBATE EXPRESS (10 min):**\\n"Vamos abrir a roda: Qual a primeira coisa que faz ao acordar e a última antes de dormir? É olhar o celular? Você sente que controla o aparelho ou ele te controla? Quero ouvir as opiniões sinceras de vocês!"\\n\\n✍️ **6. ATIVIDADE NO CADERNO (15 min):**\\n"Mantenham as perguntas projetadas. Respondam as 4 questões individualmente. Passarei nas carteiras dando visto e nota de participação do trimestre no caderno de todos!"\` },
        { data: '06/11', tri: '3º Tri', modulo: 'Mídias', titulo: 'Redes Sociais, Ativismo e Algoritmos', desc: 'Ativismo virtual x presencial. A bolha dos algoritmos.', resumo: \`🎯 **Objetivo da Aula:** Entender como a internet molda o que recebemos de causa social.\\n\\n🗣️ **Dinâmica:**\\n• Debate sobre ativismo de sofá.\\n• Cancelamento nas mídias sociais.\` },
        { data: '13/11', tri: '3º Tri', modulo: 'Cultura', titulo: 'Apropriação vs Intercâmbio', desc: 'A fronteira da apropriação cultural na moda, no esporte e na música.', resumo: \`🎯 **Objetivo da Aula:** Destrinchar de quem é a arte e por qual preço se adquire.\\n\\n🗣️ **Dinâmica:**\\n• Elementos tradicionais que viraram produtos comerciais.\\n• Respeito e herança.\` },
        { data: '20/11', tri: '3º Tri', modulo: 'Feriado', titulo: 'Dia da Consciência Negra', desc: 'Feriado Nacional.', resumo: \`🎯 **Objetivo da Aula:** Feriado Nacional - Sem aula.\` },
        { data: '27/11', tri: '3º Tri', modulo: 'Revisão', titulo: 'Revisão Geral e Plantão', desc: 'Repasse completo pro trimestre (Racismo, Autodeclaração, Krenak, Políticas Públicas).', resumo: \`🎯 **Objetivo da Aula:** Sistematização de saberes (Povos Originários, Lutas Sociais, Identidade).\` },
        { data: '04/12', tri: '3º Tri', modulo: 'Avaliação', titulo: 'Avaliação Final', desc: 'Prova final do Itinerário Formativo sobre Ciências Humanas.', resumo: \`🎯 **Objetivo da Aula:** Verificar o amadurecimento crítico do aluno.\` },
        { data: '11/12', tri: '3º Tri', modulo: 'Recuperação', titulo: 'Recuperação e Fechamento', desc: 'Consolidação de notas e oportunidade para reavaliação.', resumo: \`🎯 **Objetivo da Aula:** Recuperação de notas dos alunos que não alcançaram a média e fechamento de diários.\` }
    ]`;

const regex = /'ilgch': \[[\s\S]*?\](?=\n\s*};\n\s*PE_PLAN\['ciep369'\])/;
if (regex.test(content)) {
    content = content.replace(regex, newIlgch);
    fs.writeFileSync(path, content, 'utf8');
    console.log('Successfully updated ilgch array');
} else {
    console.log('Failed to find ilgch array with regex');
}
