import sys

NEW_CONTENT = """  "21/09": [
    { "id": 1, "tipo": "capa", "titulo": "Uru-Can", "subtitulo": "A Luta das Cobras Brasileiras", "imagem_url": "https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=80&w=1200&auto=format&fit=crop", "topicos": [], "notas": "Introduzir o tema. Perguntar se alguém já ouviu falar do Uru-Can. Explicar que é uma luta genuinamente brasileira." },
    { "id": 2, "tipo": "conceito", "titulo": "Origem", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=800&auto=format&fit=crop", "topicos": ["Criada na Brigada de Infantaria Paraquedista, no Rio de Janeiro", "Criador: Paulo César da Silva Lopes, militar negro e evangélico", "Criada nos anos 70 para situações reais de combate", "Mistura de Karatê, Taekwondo, Kung Fu, Judô e Jiu-Jitsu"], "notas": "Contar a história do criador. Destacar que é uma luta 100% brasileira, criada dentro dos quartéis." },
    { "id": 3, "tipo": "conceito", "titulo": "O Nome", "subtitulo": "A Junção das Cobras", "imagem_url": "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&auto=format&fit=crop", "topicos": ["O nome Uru-Can é a junção de duas cobras brasileiras", "URU de Urutu: cobra peçonhenta e agressiva", "CAN de Caninana: cobra ágil e rápida", "O nome representa a agressividade e a agilidade da luta"], "notas": "Mostrar imagens das cobras. Explicar que o nome foi escolhido para representar as qualidades da luta." },
    { "id": 4, "tipo": "conceito", "titulo": "Características", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop", "topicos": ["Foco em defesa pessoal e letalidade", "Combina golpes de percussão, projeções e imobilizações", "Inclui treinamento com armas brancas (facão, fuzil)", "Não tem regras de competição — foco no combate real"], "notas": "Explicar que o Uru-Can não é uma luta esportiva, mas sim uma arte de combate. Mostrar a diferença para o Jiu-Jitsu." },
    { "id": 5, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Huka-Huka", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=80&w=800&auto=format&fit=crop", "topicos": ["Vamos conhecer a luta ritualística dos povos indígenas do Xingu", "Pesquisar: O que é o Kuarup?"], "notas": "Criar expectativa para a próxima aula." }
  ],
  "28/09": [
    { "id": 1, "tipo": "capa", "titulo": "Huka-Huka", "subtitulo": "A Luta Ritualística dos Povos do Xingu", "imagem_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop", "topicos": [], "notas": "Introduzir o tema. Contextualizar que é uma luta indígena com forte significado cultural." },
    { "id": 2, "tipo": "conceito", "titulo": "Origem e Significado", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=800&auto=format&fit=crop", "topicos": ["Luta tradicional dos povos do Alto Xingu (Mato Grosso)", "Praticada no ritual do Kuarup, celebração da vida e da paz", "O nome refere-se ao som emitido pelos lutadores imitando o rugido da onça", "Representa um rito de passagem para a vida adulta"], "notas": "Explicar o contexto ritual. Mostrar que não é só uma competição, é uma celebração." },
    { "id": 3, "tipo": "conceito", "titulo": "Como Funciona a Luta?", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop", "topicos": ["Realizada de joelhos", "Movimentos rápidos e fluidos", "Técnicas de desequilíbrio, projeção e imobilização", "Proibidos: socos, chutes, joelhadas, mordidas e puxões de cabelo", "Duração de até 2 minutos, sem árbitros"], "notas": "Detalhar as regras. Explicar que a luta é decidida pelos próprios lutadores, sem juiz." },
    { "id": 4, "tipo": "discussao", "titulo": "Refletindo sobre o Huka-Huka", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=80&w=800&auto=format&fit=crop", "topicos": ["O que mais chamou a atenção de vocês?", "Por que essa luta é importante para os povos indígenas?", "Como vocês acham que essa luta se diferencia das que já conhecemos?"], "notas": "Incentivar a participação da turma. Mediar a discussão." },
    { "id": 5, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Jiu-Jitsu Brasileiro", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=80&w=800&auto=format&fit=crop", "topicos": ["Vamos conhecer a luta que nasceu no Japão e se tornou brasileira", "Pesquisar: Quem foi Mitsuyo Maeda?"], "notas": "Criar expectativa para a próxima aula." }
  ],
  "05/10": [
    { "id": 1, "tipo": "capa", "titulo": "Jiu-Jitsu Brasileiro", "subtitulo": "A Luta que Conquistou o Mundo", "imagem_url": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?q=80&w=1200&auto=format&fit=crop", "topicos": [], "notas": "Introduzir o tema. Mostrar a importância global do JJB." },
    { "id": 2, "tipo": "conceito", "titulo": "Origens", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=800&auto=format&fit=crop", "topicos": ["Arte marcial de origem japonesa", "Trazida ao Brasil por Mitsuyo Maeda no início do século XX", "Maeda ensinou a Carlos Gracie, que adaptou as técnicas", "A família Gracie desenvolveu um estilo próprio", "Ficou conhecido como Gracie Jiu-Jitsu ou Brazilian Jiu-Jitsu"], "notas": "Contar a história da família Gracie. Explicar a adaptation das técnicas." },
    { "id": 3, "tipo": "conceito", "titulo": "Características", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop", "topicos": ["Foco em lutas no chão", "Uso de alavancas e eficiência", "Técnicas de estrangulamento e chaves de braço", "Objetivo: submeter o oponente", "Ênfase na defesa pessoal e na superação da força bruta"], "notas": "Explicar a filosofia do JJB. Mostrar como a técnica supera a força." },
    { "id": 4, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Luta Livre Esportiva", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=80&w=800&auto=format&fit=crop", "topicos": ["Vamos conhecer a luta criada por Euclydes Hatem, o 'Tatu'", "Pesquisar: O que é grappling?"], "notas": "Criar expectativa para a próxima aula." }
  ],
  "19/10": [
    { "id": 1, "tipo": "capa", "titulo": "Luta Livre Esportiva", "subtitulo": "A Luta Brasileira de Euclydes Hatem", "imagem_url": "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=1200&auto=format&fit=crop", "topicos": [], "notas": "Introduzir o tema. Contextualizar a Luta Livre como uma luta genuinamente brasileira." },
    { "id": 2, "tipo": "conceito", "titulo": "Origens", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=800&auto=format&fit=crop", "topicos": ["Criada no Rio de Janeiro por Euclydes Hatem, o 'Tatu'", "Influência do catch wrestling e do jiu-jitsu", "Considerada uma luta brasileira de submission wrestling", "Foco em quedas, imobilizações e finalizações"], "notas": "Contar a história de Euclydes Hatem. Explicar a diferença para o Jiu-Jitsu." },
    { "id": 3, "tipo": "atividade", "titulo": "Revisão das Lutas Brasileiras", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=800&auto=format&fit=crop", "topicos": ["Capoeira: dança, luta e música", "Luta Marajoara: agarrada da Ilha de Marajó", "Huka-Huka: luta indígena do Xingu", "Jiu-Jitsu Brasileiro: luta no chão, família Gracie", "Uru-Can: luta das cobras, criada no Exército", "Luta Livre Esportiva: criada por Euclydes Hatem"], "notas": "Fazer um resumo rápido de cada luta. Perguntar o que lembram." },
    { "id": 4, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Ginástica de Conscientização Corporal", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=800&auto=format&fit=crop", "topicos": ["Vamos sair das lutas e entrar no mundo da ginástica", "Preparem-se para atividades de respiração e relaxamento"], "notas": "Criar expectativa para a próxima aula." }
  ],
  "26/10": [
    { "id": 1, "tipo": "capa", "titulo": "Ginástica de Conscientização Corporal", "subtitulo": "Conectando Corpo e Mente", "imagem_url": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=1200&auto=format&fit=crop", "topicos": [], "notas": "Introduzir o tema. Explicar que vamos trabalhar corpo e mente de forma integrada." },
    { "id": 2, "tipo": "conceito", "titulo": "O que é?", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=800&auto=format&fit=crop", "topicos": ["Atividades físicas que combinam movimentos lentos e suaves", "Exercícios de respiração para fortalecer a conexão corpo-mente", "Exemplos: ioga, pilates, tai chi chuan, automassagem", "Foco na percepção do próprio corpo, não no desempenho"], "notas": "Explicar que não é sobre força ou velocidade, mas sobre sentir o corpo." },
    { "id": 3, "tipo": "atividade", "titulo": "Prática em Sala", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=800&auto=format&fit=crop", "topicos": ["Respiração consciente: inspirar em 4 tempos, segurar em 4, expirar em 6", "Alongamento guiado: pescoço, ombros, braços e coluna", "Automassagem: mãos, pés e rosto", "Relaxamento final: olhos fechados, atenção na respiração"], "notas": "Conduzir a prática com voz calma. Adaptar para quem tem limitações físicas." },
    { "id": 4, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Prática de Conscientização", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=800&auto=format&fit=crop", "topicos": ["Como vocês se sentiram?", "Vocês já praticaram alguma dessas atividades?", "Próxima aula: aprofundamento na prática"], "notas": "Ouvir os alunos. Recolher impressões." }
  ],
  "09/11": [
    { "id": 1, "tipo": "capa", "titulo": "Ginástica de Conscientização", "subtitulo": "Prática e Relaxamento", "imagem_url": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=1200&auto=format&fit=crop", "topicos": [], "notas": "Retomar o que foi visto na aula anterior." },
    { "id": 2, "tipo": "atividade", "titulo": "Sequência de Práticas", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=800&auto=format&fit=crop", "topicos": ["Alongamento guiado com música suave", "Exercícios de respiração diafragmática", "Automassagem nos pés e mãos", "Meditação guiada de 5 minutos", "Roda de conversa sobre as sensações"], "notas": "Preparar o ambiente: luz baixa se possível, música calma. Conduzir com voz tranquila." },
    { "id": 3, "tipo": "reflexao", "titulo": "Benefícios", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=800&auto=format&fit=crop", "topicos": ["Redução do estresse e da ansiedade", "Melhora da concentração", "Consciência corporal e postura", "Bem-estar e qualidade de vida"], "notas": "Relacionar com o dia a dia dos alunos. Perguntar como se sentem após a prática." },
    { "id": 4, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Esportes de Rede e Parede", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=800&auto=format&fit=crop", "topicos": ["Vamos conhecer os esportes de rede e parede", "Pesquisar: O que é badminton?"], "notas": "Criar expectativa para a próxima aula." }
  ],
  "16/11": [
    { "id": 1, "tipo": "capa", "titulo": "Esportes de Rede e Parede", "subtitulo": "Jogando na Sala de Aula", "imagem_url": "https://images.unsplash.com/photo-1541872703-74c5e44368f9?q=1200&auto=format&fit=crop", "topicos": [], "notas": "Introduzir o tema. Explicar que vamos adaptar esportes de rede para a sala." },
    { "id": 2, "tipo": "conceito", "titulo": "O que são?", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=800&auto=format&fit=crop", "topicos": ["Esportes de rede: jogar a bola por cima de uma rede para o campo adversário", "Esportes de parede: rebater a bola contra uma parede de rebote", "Exemplos: vôlei, tênis de mesa, badminton, peteca, squash"], "notas": "Explicar a diferença entre rede e parede. Mostrar imagens." },
    { "id": 3, "tipo": "atividade", "titulo": "Adaptações para Sala", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=800&auto=format&fit=crop", "topicos": ["Vôlei de balão: usar bexigas em vez de bola, rede feita com barbante", "Tênis de mesa na carteira: usar livros como rede e réguas como raquetes", "Peteca de papel: confeccionar petecas com papel e jogar em duplas", "Badminton de mão: usar as mãos como raquetes"], "notas": "Organizar a turma em duplas ou trios. Adaptar conforme o espaço da sala." },
    { "id": 4, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Danças Urbanas", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=800&auto=format&fit=crop", "topicos": ["Vamos entrar no mundo do Hip Hop e das danças urbanas", "Pesquisar: Quais são os estilos de dança urbana?"], "notas": "Criar expectativa para a próxima aula." }
  ],
  "23/11": [
    { "id": 1, "tipo": "capa", "titulo": "Danças Urbanas", "subtitulo": "Hip Hop, Breakdance e Muito Mais", "imagem_url": "https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=1200&auto=format&fit=crop", "topicos": [], "notas": "Introduzir o tema. Perguntar quem já dançou ou viu danças urbanas." },
    { "id": 2, "tipo": "conceito", "titulo": "O que são Danças Urbanas?", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=800&auto=format&fit=crop", "topicos": ["Estilos de dança que surgiram nas periferias e centros urbanos", "Relacionadas à cultura Hip Hop", "Principais estilos: Locking, Wacking, Breakdance, Vogue, Hip Hop Dance", "Movimentos: Bounce, Wave, Ticking, Slide"], "notas": "Mostrar vídeos curtos de cada estilo. Explicar a origem social dessas danças." },
    { "id": 3, "tipo": "atividade", "titulo": "Vivência em Sala", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=800&auto=format&fit=crop", "topicos": ["Aquecimento: bounce e wave (movimentos básicos)", "Sequência de 6 passos para iniciantes", "Improvisação em roda: cada aluno mostra um movimento", "Criação de uma coreografia simples em grupos"], "notas": "Adaptar os movimentos para o espaço da sala. Respeitar quem não quiser dançar, mas incentivar a participação." },
    { "id": 4, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Jogos de Tabuleiro", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=800&auto=format&fit=crop", "topicos": ["Vamos criar um jogo de tabuleiro sobre o que aprendemos", "Preparem a criatividade!"], "notas": "Criar expectativa para a próxima aula." }
  ],
  "30/11": [
    { "id": 1, "tipo": "capa", "titulo": "Jogos de Tabuleiro", "subtitulo": "Criando e Aprendendo", "imagem_url": "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=1200&auto=format&fit=crop", "topicos": [], "notas": "Explicar que os alunos vão criar um jogo de tabuleiro sobre o conteúdo do trimestre." },
    { "id": 2, "tipo": "atividade", "titulo": "Criando o Jogo", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=800&auto=format&fit=crop", "topicos": ["Em grupos, criem um jogo de tabuleiro sobre as lutas, ginástica, esportes ou danças", "O jogo deve ter: tabuleiro, regras, peões e cartas de perguntas", "As perguntas devem ser sobre o que aprendemos no trimestre", "Sejam criativos!"], "notas": "Distribuir materiais: cartolina, canetas, dados, etc. Circular pela sala para ajudar." },
    { "id": 3, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Avaliação Escrita", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=800&auto=format&fit=crop", "topicos": ["Na próxima aula, teremos a avaliação escrita do trimestre", "Revisem o conteúdo!"], "notas": "Avisar sobre a avaliação. Dar dicas de estudo." }
  ],
  "07/12": [
    { "id": 1, "tipo": "capa", "titulo": "Avaliação Escrita", "subtitulo": "Mostrando o que aprendemos", "imagem_url": "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=1200&auto=format&fit=crop", "topicos": [], "notas": "Aplicar a avaliação. Manter a tranquilidade da turma." },
    { "id": 2, "tipo": "conceito", "titulo": "Instruções", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=800&auto=format&fit=crop", "topicos": ["Leia as questões com atenção", "Responda com calma e clareza", "Não é permitido consultar o material", "Boa prova!"], "notas": "Distribuir as provas. Circular pela sala para tirar dúvidas." },
    { "id": 3, "tipo": "fechamento", "titulo": "Fechamento", "subtitulo": "Próxima aula: Encerramento do Ano", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=800&auto=format&fit=crop", "topicos": ["Na próxima aula, vamos fazer uma retrospectiva do ano", "Preparem suas reflexões finais"], "notas": "Criar expectativa para a última aula." }
  ],
  "14/12": [
    { "id": 1, "tipo": "capa", "titulo": "Encerramento do Ano", "subtitulo": "Até o próximo ano!", "imagem_url": "https://images.unsplash.com/photo-1544027993-37dbfe43562a?q=1200&auto=format&fit=crop", "topicos": [], "notas": "Última aula do ano. Momento de descontração e avaliação." },
    { "id": 2, "tipo": "reflexao", "titulo": "Nossa Jornada", "subtitulo": "3º Trimestre", "imagem_url": "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?q=1200&auto=format&fit=crop", "topicos": ["Uru-Can", "Huka-Huka", "Jiu-Jitsu Brasileiro", "Luta Livre Esportiva", "Ginástica de Conscientização Corporal", "Esportes de Rede e Parede", "Danças Urbanas", "Jogos de Tabuleiro"], "notas": "Fazer uma retrospectiva do que foi estudado. Ouvir os alunos." },
    { "id": 3, "tipo": "atividade", "titulo": "Autoavaliação", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?q=800&auto=format&fit=crop", "topicos": ["O que eu aprendi neste ano?", "O que eu levo para a vida?", "Como me senti nas aulas?", "Sugestões para o próximo ano"], "notas": "Distribuir papel. Pode ser anônimo. Recolher para feedback." },
    { "id": 4, "tipo": "fechamento", "titulo": "Mensagem Final", "subtitulo": "", "imagem_url": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?q=800&auto=format&fit=crop", "topicos": ["Você é importante", "Cuide da sua saúde mental", "Boas festas e um excelente 2027!"], "notas": "Encerrar com acolhimento e votos de boas festas." }
  ]"""

with open("data/corpoMidiaSlides.ts", "r") as f:
    content = f.read()

start_marker = "export const SLIDES_LUTAS_BRASIL_8ANO_3TRI: Record<string, any[]> = {"
end_marker = "export const ALTINHA_FUTVOLEI_SLIDES ="

start_idx = content.find(start_marker)
end_idx = content.find(end_marker, start_idx)

if start_idx != -1 and end_idx != -1:
    obj_end_idx = content.rfind("};", start_idx, end_idx)
    if obj_end_idx != -1:
        new_obj = start_marker + "\n" + NEW_CONTENT + "\n};"
        new_content = content[:start_idx] + new_obj + content[obj_end_idx+2:]
        with open("data/corpoMidiaSlides.ts", "w") as f:
            f.write(new_content)
        print("Successfully updated SLIDES_LUTAS_BRASIL_8ANO_3TRI")
    else:
        print("Failed to find closing brace")
        sys.exit(1)
else:
    print(f"Failed to find markers: start={start_idx}, end={end_idx}")
    sys.exit(1)
